# https://rmoff.net/2020/12/20/scheduling-hugo-builds-on-github-pages-with-github-actions/

name: learn-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.80.0'
    - name: Build
      run: cd dolinar && rm -fr public && hugo && find ./public/ -type f
